version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app
    environment:
      DATABASE_URL: database_url
    